{
 "title": "Client Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ns", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (type) (up{service=~\".*-gateway\",namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "UAAs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (type) (up{service=~\".*-uaa\",namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Reports",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (type) (up{service=~\".*-report\",namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Gateway Alive",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (type) (process_uptime_seconds{service=~\".*-gateway\"})"
    }
   ]
  },
  {
   "title": "UAA Alive",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (type) (process_uptime_seconds{service=~\".*-uaa\"})"
    }
   ]
  },
  {
   "title": "Report Alive",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (type) (process_uptime_seconds{service=~\".*-report\"})"
    }
   ]
  },
  {
   "title": "Network Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(logback_events_total{level=\"error\"}[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-gateway\",area=\"heap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-gateway\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-gateway\",area=\"nonheap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-gateway\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (system_cpu_usage{service=~\".*-gateway\"}) + sum by (type) (process_cpu_usage{service=~\".*-gateway\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum by (type) (system_load_average_1m{service=~\".*-gateway\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "sum by (type) (system_cpu_count{service=~\".*-gateway\"})",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "G1 Survivor Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-gateway\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-gateway\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-gateway\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Activations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{service=~\".*-gateway\"}[5m])",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "G1 Old Gen Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-gateway\",id=\"G1 Old Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-gateway\",id=\"G1 Old Gen\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-gateway\",id=\"G1 Old Gen\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Eden Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-gateway\",id=\"G1 Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-gateway\",id=\"G1 Eden Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-gateway\",id=\"G1 Eden Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "UAA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-uaa\",area=\"heap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-uaa\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-uaa\",area=\"nonheap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-uaa\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (system_cpu_usage{service=~\".*-uaa\"}) + sum by (type) (process_cpu_usage{service=~\".*-uaa\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "sum by (type) (system_load_average_1m{service=~\".*-uaa\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "sum by (type) (system_cpu_count{service=~\".*-uaa\"})",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "G1 Survivor Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-uaa\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-uaa\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-uaa\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Activations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{service=~\".*-uaa\"}[5m])",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "G1 Old Gen Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-uaa\",id=\"G1 Old Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-uaa\",id=\"G1 Old Gen\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-uaa\",id=\"G1 Old Gen\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Eden Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-uaa\",id=\"G1 Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-uaa\",id=\"G1 Eden Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-uaa\",id=\"G1 Eden Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (hikaricp_connections{service=~\".*-uaa\"})"
    }
   ]
  },
  {
   "title": "DB Connections Active",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (hikaricp_connections_active{service=~\".*-uaa\"})"
    }
   ]
  },
  {
   "title": "DB Connections Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_count{service=~\".*-uaa\"}[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-report\",area=\"heap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-report\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-report\",area=\"nonheap\"})*100/sum by (type) (jvm_memory_max_bytes{service=~\".*-report\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (system_cpu_usage{service=~\".*-report\"}) + sum by (type) (process_cpu_usage{service=~\".*-report\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 54 },
   "targets": [
    {
     "expr": "sum by (type) (system_load_average_1m{service=~\".*-report\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "sum by (type) (system_cpu_count{service=~\".*-report\"})",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "G1 Survivor Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-report\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-report\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-report\",id=\"G1 Survivor Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Activations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{service=~\".*-report\"}[5m])",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "G1 Eden Space Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-report\",id=\"G1 Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-report\",id=\"G1 Eden Space\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-report\",id=\"G1 Eden Space\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Old Gen Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (jvm_memory_used_bytes{service=~\".*-report\",id=\"G1 Old Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (type) (jvm_memory_committed_bytes{service=~\".*-report\",id=\"G1 Old Gen\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum by (type) (jvm_memory_max_bytes{service=~\".*-report\",id=\"G1 Old Gen\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (hikaricp_connections{service=~\".*-report\"})"
    }
   ]
  },
  {
   "title": "DB Connections Active",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (hikaricp_connections_active{service=~\".*-report\"})"
    }
   ]
  },
  {
   "title": "DB Connections Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_count{service=~\".*-report\"}[15s])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Scheduler Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(allure_scheduler_blob_remove_task_seconds_count[5m])",
     "legendFormat": "Blob Remove Task"
    },
    {
     "expr": "rate(allure_scheduler_cleaner_schema_seconds_count[5m])",
     "legendFormat": "Cleaner Schema"
    },
    {
     "expr": "rate(allure_scheduler_global_cleaner_schema_seconds_count[5m])",
     "legendFormat": "Global Cleaner Schema"
    },
    {
     "expr": "rate(allure_scheduler_launch_close_seconds_count[5m])",
     "legendFormat": "Launch Close"
    },
    {
     "expr": "rate(allure_scheduler_project_trend_seconds_count[5m])",
     "legendFormat": "Project Trend"
    }
   ]
  },
  {
   "title": "Files Processing Timing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(allure_upload_process_seconds_count[5m])",
     "legendFormat": "Process"
    },
    {
     "expr": "rate(allure_upload_complete_process_seconds_count[5m])",
     "legendFormat": "Complete Process"
    },
    {
     "expr": "rate(allure_upload_post_process_seconds_count[5m])",
     "legendFormat": "Post Process"
    }
   ]
  },
  {
   "title": "Files OPS Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(allure_blob_storage_copy_seconds_count[5m])",
     "legendFormat": "Copy"
    },
    {
     "expr": "rate(allure_blob_storage_find_seconds_count[5m])",
     "legendFormat": "Find"
    },
    {
     "expr": "rate(allure_blob_storage_read_seconds_count[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(allure_blob_storage_remove_seconds_count[5m])",
     "legendFormat": "Remove"
    },
    {
     "expr": "rate(allure_blob_storage_store_seconds_count[5m])",
     "legendFormat": "Store"
    }
   ]
  }
 ]
}