{
 "title": "Minio",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(minio_process_cpu_seconds_total[15s])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "rate(minio_s3_requests_total[15s])",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_s3_traffic_sent_bytes[15s])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(minio_s3_traffic_received_bytes[15s])",
     "legendFormat": "Recieved"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "File Descriptors Open",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minio_process_open_fds", "legendFormat": "open" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_s3_requests_errors_total[15s])",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}