{
 "title": "Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(server)" } },
   { "name": "service", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"report\"} - 1",
     "legendFormat": "report"
    },
    {
     "expr": "pg_stat_database_numbackends{datname=\"uaa\"} - 1",
     "legendFormat": "uaa"
    }
   ]
  },
  {
   "title": "Block Write Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_write_time{datname=\"report\"}[15s])",
     "legendFormat": "report"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{datname=\"uaa\"}[15s])",
     "legendFormat": "uaa"
    }
   ]
  },
  {
   "title": "Block Read Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=\"report\"}[15s])",
     "legendFormat": "report"
    },
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=\"uaa\"}[15s])",
     "legendFormat": "uaa"
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_sessions{datname=\"$service\"}[15s])"
    },
    { "expr": "pg_stat_da" }
   ]
  },
  {
   "title": "Abandoned Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_sessions_abandoned{datname=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Fatal Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_sessions_fatal{datname=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Killed Sessions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_sessions_killed{datname=\"$service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_conflicts{datname=\"$service\"}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"$service\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"$service\"}[15s])",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"$service\"}[15s])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"$service\"}[15s])",
     "legendFormat": "Updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"$service\"}[15s])",
     "legendFormat": "Returned"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"$service\"}[15s])",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Temp Files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_files{datname=\"$service\"}[15s])"
    }
   ]
  },
  {
   "title": "Temp Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{datname=\"$service\"}[15s])"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$service\"}[15s])",
     "legendFormat": "commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$service\"}[15s])",
     "legendFormat": "rollbacks"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"$service\"}[15s])",
     "legendFormat": "rows inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"$service\"}[15s])",
     "legendFormat": "rows fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"$service\"}[15s])",
     "legendFormat": "rows returned"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"$service\"}[15s])",
     "legendFormat": "rows deleted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"$service\"}[15s])",
     "legendFormat": "rows updated"
    }
   ]
  },
  {
   "title": "Autovacuum Thresholds (Triggers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_autovacuum_analyze_threshold{server=\"$server\"}",
     "legendFormat": "analyse"
    },
    {
     "expr": "pg_settings_autovacuum_vacuum_insert_threshold{server=\"$server\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "pg_settings_autovacuum_vacuum_threshold{server=\"$server\"}",
     "legendFormat": "vacuum"
    }
   ]
  },
  {
   "title": "Background Writer Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{server=\"$server\"}[15s])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend{server=\"$server\"}[15s])",
     "legendFormat": "written"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{server=\"$server\"}[15s])",
     "legendFormat": "fsyncs"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{server=\"$server\"}[15s])",
     "legendFormat": "checkpoints"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_clean{server=\"$server\"}[15s])",
     "legendFormat": "clean"
    }
   ]
  }
 ]
}