{
 "title": "Rabbit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_uptime" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connections" }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_consumers" }
   ]
  },
  {
   "title": "Messages Published",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[15s])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Ack",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_ack_total[15s])",
     "legendFormat": "{{queue}}"
    },
    {}
   ]
  },
  {
   "title": "Redelivered Messages",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_redelivered_total[15s])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queues Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rabbitmq_queue_memory", "legendFormat": "{{queue}}" }
   ]
  }
 ]
}